version: '3'

services: 
  
  wp-front:
    build: 
      context: .
      dockerfile: Dockerfile
    image: wp-front
    container_name: wp-front
    hostname: wp-front
    entrypoint: docker-entrypoint.sh yarn start
    networks: 
      - wpp-network
    tty: true
    ports:
      - '3002:3002'
    
networks: 
  wpp-network:
    name: wpp-network
    driver: bridge 